# Generated by Django 5.2 on 2025-05-10 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloads', '0003_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='file_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='app',
            name='image_utl',
            field=models.URLField(blank=True, null=True),
        ),
    ]
