# Generated by Django 5.2 on 2025-05-10 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloads', '0004_app_file_url_app_image_utl'),
    ]

    operations = [
        migrations.RenameField(
            model_name='app',
            old_name='image_utl',
            new_name='image_url',
        ),
        migrations.RemoveField(
            model_name='app',
            name='file',
        ),
        migrations.RemoveField(
            model_name='app',
            name='image',
        ),
        migrations.AlterField(
            model_name='app',
            name='platform',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='downloads.platform'),
        ),
    ]
