# Generated by Django 5.2 on 2025-05-19 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloads', '0005_rename_image_utl_app_image_url_remove_app_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='app_type',
            field=models.CharField(choices=[('app', 'app'), ('game', 'game')], default='app', max_length=50),
            preserve_default=False,
        ),
    ]
