# Generated by Django 5.2 on 2025-05-22 15:40

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('downloads', '0006_app_app_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='app',
            old_name='description',
            new_name='meta_description',
        ),
        migrations.AddField(
            model_name='app',
            name='long_description',
            field=django_ckeditor_5.fields.CKEditor5Field(default=' '),
            preserve_default=False,
        ),
    ]
