# Generated by Django 5.2 on 2025-06-26 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('downloads', '0007_rename_description_app_meta_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='app',
            old_name='license',
            new_name='licence',
        ),
    ]
