# Generated by Django 5.2 on 2025-07-31 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloads', '0011_remove_app_downloads_remove_app_file_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='download',
            name='app',
        ),
        migrations.AddField(
            model_name='download',
            name='app_version',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='downloads.appversion'),
            preserve_default=False,
        ),
    ]
